{
 "title": "U131",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Net I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EBS disc I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "VolumeReadOps",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "VolumeWriteBytes",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "VolumeWriteOps",
     "namespace": "AWS/EBS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}