---

- name: Übung 127
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install Apache (Amazon Linux)
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.import_tasks: redhat.yaml

    - name: Install Apache (Ubuntu)
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.import_tasks:
        debian.yaml

  handlers:
    - name: File copied
      ansible.builtin.debug:
        msg: "Index.html copied on {{ ansible_facts['distribution'] }}"

...
