---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    name: "*"
    state: latest # noqa package-latest

- name: "Install {{ service }}"
  ansible.builtin.apt:
    name: "{{ service }}"
    state: "latest" # noqa package-latest

- name: "Copy {{ service }} alert rules"
  ansible.builtin.copy:
    src: files/alert_node_down.yaml
    dest: "{{ prometheus_config_path }}/alertmanager_templates/"
    mode: '0644'
  notify:
    - Restart nginx

- name: "Copy {{ service }} config"
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    mode: "0644"
  notify:
    - Restart nginx

- name: "Start {{ service }} server"
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: true
    state: started
