version: '3'
# 
# services:
#   web:
#     image: "nginx:latest"
#     ports:
#       - "8080:80"
#     volumes:
#       - "./src:/usr/share/nginx/html"


services:
  db:
    image: mariadb:11.1.2
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-net
    restart: always

  wordpress:
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8080:80"
    networks:
      - wp-net
    restart: always

volumes:
  db_data:

networks:
  wp-net: {}
