version: '3'

services:
  db:
    image: mariadb:11.1.2
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=restaurants
      - MYSQL_USER=example-user
      - MYSQL_PASSWORD=my_cool_secret
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

  api:
    build: ./
    networks:
      - app_net
    restart: unless-stopped
    ports: 
      - "3000:3000"
    depends_on:
      db:
        condition: service_started

volumes:
  db_data: {}

networks:
  app_net: {}
