---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    name: "*"
    state: latest # noqa package-latest

- name: "Install {{ service }}"
  ansible.builtin.apt:
    name: "{{ service }}"
    state: "latest" # noqa package-latest

- name: "Start {{ service }} daemon"
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: true
    state: restarted
