---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    name: "*" # noqa package-latest
    state: latest

- name: Add {{ service }} GPG Key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add {{ service }} Repo
  ansible.builtin.apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present

- name: "Install {{ service }}"
  ansible.builtin.apt:
    name: "{{ service | lower }}"
    state: "latest" # noqa package-latest
    update_cache: true

- name: Copy {{ service }} config files
  ansible.builtin.copy:
    mode: "0644"
    src: files/grafana.ini
    dest: /etc/grafana/grafana.ini

- name: Installing AWS credentials
  ansible.builtin.template:
    src: templates/credentials.j2
    dest: /usr/share/grafana/.aws/
    mode: "0640"

- name: Start grafana-server
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: restarted
