---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    name: "*"
    state: latest # noqa package-latest

- name: Install Prometheus
  ansible.builtin.apt:
    name: "prometheus"
    state: "latest" # noqa package-latest

- name: Copy Prometheus config file
  ansible.builtin.template:
    src: files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"

- name: Copy Prometheus config files
  ansible.builtin.copy:
    src: files/alert_node_down.yaml
    dest: /etc/prometheus/alertmanager_templates/
    mode: "0644"

- name: Start promeheus server
  ansible.builtin.service:
    name: prometheus
    enabled: true
    state: restarted
