CREATE TABLE IF NOT EXISTS Buecherei.Wohnort(
	PLZ_ID INT NOT NULL PRIMARY KEY, 
	PLZ VARCHAR(30) NOT NULL,
	ORT VARCHAR(30) NOT NULL);

CREATE TABLE Buecherei.Autor(
	AUTOR_ID INT NOT NULL PRIMARY KEY,
	Autorvorname VARCHAR (50) NOT NULL,
	Autornachname VARCHAR (50) NOT NULL);

CREATE TABLE Buecherei.Kategorie(
	KATEGORIE_ID INT NOT NULL PRIMARY KEY,
	Kategoriename VARCHAR (30) NOT NULL);

CREATE TABLE Buecherei.Jahr(
	JAHR_ID INT NOT NULL PRIMARY KEY,
	Jahreszahl VARCHAR (10));

CREATE TABLE Buecherei.Verlag(
	VERLAG_ID INT NOT NULL PRIMARY KEY,
	Verlagname VARCHAR (50));
	
CREATE TABLE Buecherei.Buch(
	ISBN INT NOT NULL PRIMARY KEY,
	Titel VARCHAR(100) NOT NULL,
	Autor INT,
	Jahr INT,
	Verlag INT,
	Kategorie INT,
	Verfügbarkeit VARCHAR(10),
	FOREIGN KEY (Autor) REFERENCES Autor(AUTOR_ID),
	FOREIGN KEY (Jahr) REFERENCES Jahr(JAHR_ID),
	FOREIGN KEY (Verlag) REFERENCES Verlag(VERLAG_ID),
	FOREIGN KEY (Kategorie) REFERENCES Kategorie(KATEGORIE_ID));
	
CREATE TABLE Buecherei.Kunde(
	KUNDEN_ID INT NOT NULL PRIMARY KEY,
	Vorname VARCHAR(30) NOT NULL,
	Nachname VARCHAR(30) NOT NULL,
	Geburtsdatum DATE NOT NULL,
	Straße VARCHAR (100) NOT NULL,
	PLZ INT,
	FOREIGN KEY (PLZ) REFERENCES Wohnort(PLZ_ID));

CREATE TABLE Buecherei.Ausleihen(
	AUSLEIH_ID INT NOT NULL PRIMARY KEY,
	ISBN INT NOT NULL,
	Ausgeliehen_Am DATE NOT NULL,
	Ausgeliehen_Von INT NOT NULL,
	Rückgabe_Am DATE,
	FOREIGN KEY (ISBN) REFERENCES Buch(ISBN),
	FOREIGN KEY (Ausgeliehen_von) REFERENCES Kunde(KUNDEN_ID));
	
